name: Build & test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0.6
        env:
          MONGO_INITDB_ROOT_USERNAME: test-user
          MONGO_INITDB_ROOT_PASSWORD: test-password
          MONGO_INITDB_DATABASE: gestishop
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Yarn install
        run: yarn install && cd ./src && yarn install && cd ..

      - name: Yarn build
        run: yarn build

      - name: Components tests
        run: yarn components-test

      - name: End-to-end tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" -- yarn e2e-test

      - name: Upload e2e-test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-results
          path: ./out/test-results
